# Offense count: 2
# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 100

# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Enabled: false

Metrics/BlockLength:
    Max: 39
